### ISSUE TITLE
Unable to finish installation

### ISSUE THREAD

**Issue by antoniojveraa** [chris1111/Create-Install-Media-V2#1]
Hi Chris,
I'm trying to install just Clover in my Pendrive and I'm getting this error:
![Captura de pantalla 2021-01-29 a las 11 37 54 a  m](https://user-images.githubusercontent.com/69108535/106264999-b7641180-6226-11eb-9869-360d887d1071.png)
One more thing, will this Clover work in my HP Probook 4440s (i3 3rd gen) without any modifications?

**Comment by chris1111** [comment]
Cheek your USB pen  as you see on Video there is no problem  
I Just test now no issue Also I test new release Clover r5129
![Capture d’écran, le 2021-01-29 à 06 21 07](https://user-images.githubusercontent.com/6248794/106269297-56264900-61fa-11eb-94a0-a39cc95eef82.png)

**Comment by antoniojveraa** [comment]
I changed my pendrive and same result. I also tried to install Clover into my Big Sur HD and same problem. Files are copied to EFI partition but there is a problem with scrips so I don't know if this part of installation modifies the config.plist.
When I boot from this Clover I get kernel panic and it is to fast to see where the problem is.

**Comment by chris1111** [comment]
SIP is not completely disable
